FROM python:3.12
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
COPY . /app

#CMD ["python3", "manager.py"]
CMD ["flask", "--app", "main", "run"]
