version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "flask --app main run -h 0.0.0.0"
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python3 consumer.py'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    healthcheck:
      test: [ "CMD", "/usr/bin/mysql", "--user=root",  "--password=root", "--execute", "SHOW DATABASES;" ]
      interval: 10s
      timeout: 10s
      retries: 10